services:
  - type: web
    name: africa-opportuscan
    runtime: node
    plan: free
    buildCommand: npm install --prefix africa-opportuscan
    startCommand: node dashboard/server.js
    autoDeploy: true
